[tox]
envlist =
    py3.{12,11,10,9,8}
    minimal
    typing
    style
    docs
skip_missing_interpreters = true

[testenv]
package = wheel
runner = uv-venv-lock-runner
wheel_build_env = .pkg
constrain_package_deps = true
use_frozen_constraints = true
dependency_groups = tests
commands = pytest -v --tb=short --basetemp={envtmpdir} {posargs}

[testenv:minimal]
deps =
commands = python -c "from flask_principal import Principal"

[testenv:style]
dependency_groups = pre-commit
skip_install = true
commands = pre-commit run --all-files

[testenv:typing]
dependency_groups = typing
commands =
    mypy src
    pyright src

[testenv:docs]
dependency_groups = docs
commands = sphinx-build -E -W -b dirhtml docs docs/_build/dirhtml

[testenv:update-gh-actions]
labels = update
dependency_groups = gha-update
skip_install = true
commands = gha-update

[testenv:update-pre-commit]
labels = update
dependency_groups = pre-commit
skip_install = true
commands = pre-commit autoupdate -j4

[testenv:update-requirements]
labels = update
skip_install = true
commands = uv lock {posargs:-U}
